Repository metallum-ultorum/IntoTheDeep, pull requests merged in 2024-11, with the labels that each got.

#9 Self correcting odometry fix
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Settings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/systems/Odometry.java
Labels: enhancement

#31 Changed some stuff and added comments to improve the path
  MeepMeepTesting/src/main/java/com/example/meepmeeptesting/IdealLoop.java
Labels: enhancement

#30 Meet 2 integrations
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BaseRobot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainAuto.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Settings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/mechanisms/Arm.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/mechanisms/submechanisms/Shoulder.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/systems/DynamicInput.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/systems/Shortcuts.java
Labels: enhancement, PROGRAMMING, waiting

#27 Add Roadrunner
  MeepMeepTesting/.gitignore
  MeepMeepTesting/build.gradle
  MeepMeepTesting/src/main/java/com/example/meepmeeptesting/IdealLoop.java
  MeepMeepTesting/src/main/java/com/example/meepmeeptesting/ParkImmediately.java
  TeamCode/build.gradle
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoBase.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BaseRobot.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/CheckSuite.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MainAuto.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/MeetTwoStableAuto.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RoadRunnerAuto.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Settings.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestServoExtensor.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TestingSuite.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/mechanisms/submechanisms/Wrist.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/Drawing.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/Localizer.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/MecanumDrive.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/TankDrive.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/ThreeDeadWheelLocalizer.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/TwoDeadWheelLocalizer.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/DriveCommandMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/MecanumCommandMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/MecanumLocalizerInputsMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/PoseMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/TankCommandMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/TankLocalizerInputsMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/ThreeDeadWheelInputsMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/messages/TwoDeadWheelInputsMessage.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/tuning/FreakyTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/tuning/LocalizationTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/tuning/ManualFeedbackTuner.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/tuning/SplineTest.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/roadrunner/tuning/TuningOpModes.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/systems/DynamicInput.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/systems/Logger.java
  build.dependencies.gradle
  build.gradle
  settings.gradle
Labels: enhancement, PROGRAMMING, new
